### PR TITLE
Allow patterns as keys

### PR DESCRIPTION
**Pull request by getand**
This was an idea I had a while ago. What do you guys think. Could be quite nice an we do have the use case actually in application service.

```ruby
        subject.register(/\d+/, 'This must be a number')
        subject.register(/\w+/, 'This must be a string')

        expect(subject.resolve('123')).to eq('This must be a number')
        expect(subject.resolve('Lütfi')).to eq('This must be a string')
```

### CODE REVIEW

**Review by nsommer — APPROVED** [review]
Love it ❤️

**Review by AkihikoITOH — APPROVED** [review]
❤️ 

Probably it's a good idea to add something about this to README as well. Especially a short note about the order of precedence (keys having precedence over patterns, first matching pattern takes precedence over other patterns) would be helpful I think.

**Review by ston1x — APPROVED** [review]

**Comment by getand** [comment]
> ❤️
> 
> Probably it's a good idea to add something about this to README as well. Especially a short note about the order of precedence (keys having precedence over patterns, first matching pattern takes precedence over other patterns) would be helpful I think.

Yeah I wanted your opinions first. But since you guys approve I will update it.

**Comment by getand** [comment]
@AkihikoITOH You think it's better to do in the defined order? Meaning match by definition?

**Comment by AkihikoITOH** [comment]
> @AkihikoITOH You think it's better to do in the defined order? Meaning match by definition order?

Honestly I'm fine with either order as long as it's explicitly written down 😄

**Comment by AkihikoITOH** [comment]
@getand Can we get this merged?

**Pull request merged**
